name: Release
on:
  workflow_run:
    workflows: ['CI']
    branches: [master]
    types: [completed]

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: NPM Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: scttcper/github-actions/.github/workflows/npm-release.yml@313c36a2eaa9cc8c2b72876da0a1f9dd730b9d4d
    secrets:
      GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
